### ISSUE TITLE
Crash on iOS version 1.0.9 when Internet is turned off

### ISSUE THREAD

**Issue by pedrofneves** [newrelic/newrelic-flutter-agent#102]
When Flight mode is turned on or wifi/5g is turned off and open the app, the app crashes.

The problem appear to be in native library version 7.4.11. Probably when new relic tries to send data to server (and there no Internet connection).

The log on crash:

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'data parameter is nil'
*** First throw call stack:
(0x188d94f20 0x180c46018 0x187cb7b50 0x109a8bdac 0x109acf644 0x109acef98 0x109a7da14 0x10631341c 0x106310bfc 0x10a7e33d0 0x10a25fd38 0x1098e0b98 0x1098e27bc 0x1098f2d58 0x1098f290c 0x188d67710 0x188d64914 0x188d63cd8 0x1cdc141a8 0x18b39c90c 0x18b4509d0 0x18b5ca384 0x1053679c0 0x105367938 0x105367ea0 0x1ac415e4c)

**Comment by tairoroberto** [comment]
Same here

**Comment by tairoroberto** [comment]
In the Flutter plugin, I commented on these three parameters, and the app works again.

// Optional: Enable or disable offline data storage when no internet connection is available.
**offlineStorageEnabled**:true,

// iOS Specific
// Optional: Enable or disable background reporting functionality.
**backgroundReportingEnabled**: true,

// iOS Specific 
// Optional: Enable or disable to use our new, more stable, event system for iOS agent.
**newEventSystemEnabled**: true

**Comment by ndesai-newrelic** [comment]
@tairoroberto  we will look into it. thanks for feedback

**Comment by ndesai-newrelic** [comment]
@pedrofneves this is fix in latest flutter release.
