### ISSUE TITLE
 Failed resolution of: Lcom/newrelic/agent/android/instrumentation/LogInstrumentation;

### ISSUE THREAD

**Issue by cyberail** [newrelic/newrelic-flutter-agent#105]
I am receiving this issue while trying to build the app.

E/AndroidRuntime(16423): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/newrelic/agent/android/instrumentation/LogInstrumentation;
E/AndroidRuntime(16423): 	at com.google.firebase.FirebaseApp.initializeAllApis(FirebaseApp.java:606)
E/AndroidRuntime(16423): 	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:300)
E/AndroidRuntime(16423): 	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:264)
E/AndroidRuntime(16423): 	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:249)
E/AndroidRuntime(16423): 	at com.google.firebase.provider.FirebaseInitProvider.onCreate(FirebaseInitProvider.java:69)
E/AndroidRuntime(16423): 	at android.content.ContentProvider.attachInfo(ContentProvider.java:2690)
E/AndroidRuntime(16423): 	at android.content.ContentProvider.attachInfo(ContentProvider.java:2660)
E/AndroidRuntime(16423): 	at com.google.firebase.provider.FirebaseInitProvider.attachInfo(FirebaseInitProvider.java:61)
E/AndroidRuntime(16423): 	at android.app.ActivityThread.installProvider(ActivityThread.java:8458)
E/AndroidRuntime(16423): 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7963)
E/AndroidRuntime(16423): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7649)
E/AndroidRuntime(16423): 	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
E/AndroidRuntime(16423): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2478)
E/AndroidRuntime(16423): 	at android.os.Handler.dispatchMessage(Handler.java:106)

**Comment by ndesai-newrelic** [comment]
@cyberail can you update your newrelic classpath at project level to latest 7.5.0 or higher?
