### ISSUE TITLE
Custom attributes not passed along `recordError` on iOS

### ISSUE THREAD

**Issue by akaegi** [newrelic/newrelic-flutter-agent#113]
I wanted to pass along a custom `message` attribute with `recordError`. This works fine on Android but not on iOS (tested with both iOS simulator and a real iOS phone). The **message column is empty** for iOS.

![image](https://github.com/user-attachments/assets/b8a3d9db-2430-4719-84c0-881e79bc5530)

Also I don't understand why ExceptionName is different for iOS/Android and why some columns (e.g. `Is Fatal` is empty for iOS).

Also `Mobile Dart Errors` does not seem to be written for Android, is that correct?
```
FROM `Mobile Dart Errors` SELECT * SINCE 1 day ago
```

```
NewrelicMobile.instance.recordError(
      errorObject,
      stackTrace,
      attributes: {
        'message': 'Additional message',
      },
      isFatal: false,
    );
```

**Comment by ndesai-newrelic** [comment]
@akaegi thank you for reporting the issue, we will release fix in next release.

**Comment by akaegi** [comment]
FYI: I've set `newEventSystemEnabled: true` in my newrelic `Config`, not sure if that's anything to do with the issue.

**Comment by ndesai-newrelic** [comment]
@akaegi we fixed the issue on our side, we will release it soon.
