### ISSUE TITLE
Unable to find Flutter logs on NewRelic dashboard

### ISSUE THREAD

**Issue by akaegi** [newrelic/newrelic-flutter-agent#115]
I am unable to find logs in NewRelic dashboard for my Flutter mobile app (Android).
Logcat reports that report is sent to NewRelic:
```
newrelic: {level=ERROR,message=[DevActionsView] Demo fatal error message}
```

However I don't find the logs in the dashboard, not when querying like this (as read in your forum): 
```
SELECT * FROM `Mobile Dart Console Events` SINCE 1 day AGO
```
and also not in the "Logs" tab:
![image](https://github.com/user-attachments/assets/7b55147b-0a52-4713-a5ba-a37e3af4e396)

I tried to enable Logs in the "Application Settings" but that didn't help either
![image](https://github.com/user-attachments/assets/c5de9652-1aed-44ad-aed3-0e25c468e013)

What am I doing wrong, am I looking at the wrong "table"?

**Comment by akaegi** [comment]
Hi @ndesai-newrelic, I guess you mean the HTTP proxy tool Charles, right?
I did a session with Proxyman and an iOS simulator, on my Android I didn't succeed with that...

- Errors are reported correctly (NewrelicMobile.recordError) - I can see them in the Dashboard. I suspect these are the POSTs to `https://mobile-collector.eu01.nr-data.net/mobile/f`
- However for logs (NewrelicMobile.log) I don't see anything in the Dashboard, and also not in Proxyman. (I suspect the data POSTs are for analytics only?)

![Screenshot 2024-10-02 at 13 29 21](https://github.com/user-attachments/assets/3980a01c-b277-425b-b54a-125176516d1e)

![Screenshot 2024-10-02 at 13 30 04](https://github.com/user-attachments/assets/fc4232af-b6e8-4dd4-9b6c-d55cf76423b4)

<img width="1491" alt="Screenshot 2024-10-02 at 13 30 29" src="https://github.com/user-attachments/assets/2f874fc1-3927-4581-a760-b8368bf45bb0">

New relic configuration in Flutter:
```
Config newRelicConfiguration(String appToken) => Config(
      accessToken: appToken,
      //(Android only) Enable or disable collection of event data.
      analyticsEventEnabled: false,
      // https://docs.newrelic.com/docs/mobile-monitoring/new-relic-mobile/mobile-sdk/configure-settings/#flutter
      backgroundReportingEnabled: false,
      // Enable or disable crash reporting.
      crashReportingEnabled: true,
      distributedTracingEnabled: false,
      httpInstrumentationEnabled: false,
      httpResponseBodyCaptureEnabled: false,
      interactionTracingEnabled: false,
      loggingEnabled: true,
      logLevel: LogLevel.INFO,
      networkErrorRequestEnabled: false,
      networkRequestEnabled: false,
      // (iOS Specific) Optional: Enable or disable to use our new, more stable, event system for iOS agent.
      newEventSystemEnabled: true,
      // Enable or disable offline data storage when no internet connection is available.
      // To configure the amount of offline storage, see https://docs.newrelic.com/docs/mobile-monitoring/new-relic-mobile/mobile-sdk/set-max-offline-storage/#flutter.
      offlineStorageEnabled: true,
      printStatementAsEventsEnabled: false,
      webViewInstrumentation: false,
    );
```

**Comment by ndesai-newrelic** [comment]
@akaegi can you check you mobile logs settings one more time?

**Comment by akaegi** [comment]
They look like this in both applications:
![image](https://github.com/user-attachments/assets/a4baef78-dec9-4623-bc2f-731cedee2cf3)

**Comment by ndesai-newrelic** [comment]
@akaegi we are unable to reproduce it from our side, if possible can you share sample app where you reproduce the issue?

**Comment by akaegi** [comment]
Ok thank you @ndesai-newrelic ! I've seen the `sessionId` in the log entry. How can I look up the `userId` and other attributes tied to the `sessionId` (in the dashboard) (or attach it if that's not done automatically). Sorry, maybe you can just hint me at the relevant docs 😬
