### ISSUE TITLE
Failed resolution of: Lcom/newrelic/agent/android/instrumentation/LogInstrumentation

### ISSUE THREAD

**Issue by jvega-omnipro** [newrelic/newrelic-flutter-agent#122]
Hi, I'm using

newrelic_mobile: 1.1.4

settings.gradle
![Captura de pantalla 2024-10-18 a la(s) 2 46 21 p  m](https://github.com/user-attachments/assets/133978ce-2d8f-47d7-84cb-48d4eab71795)

app/build.gradle
![Captura de pantalla 2024-10-18 a la(s) 2 46 58 p  m](https://github.com/user-attachments/assets/f8502c59-a6b9-4c01-9930-e5dc44022dae)

gradle-wrapper.properties
![Captura de pantalla 2024-10-18 a la(s) 2 49 54 p  m](https://github.com/user-attachments/assets/146b2a4c-a934-4718-b0ce-b82c6ce5aba7)

It allows me to compile but when installing after a few seconds of launching the app it closes and gives me the following error

![Captura de pantalla 2024-10-18 a la(s) 2 48 28 p  m](https://github.com/user-attachments/assets/b86094ad-b642-4815-8b2b-4aac22f1a727)

I appreciate your help please

**Comment by ndesai-newrelic** [comment]
@jvega-omnipro can you share pubsec.yml  file?

**Comment by jvega-omnipro** [comment]
@ndesai-newrelic 
![Captura de pantalla 2024-10-18 a la(s) 3 18 34 p  m](https://github.com/user-attachments/assets/2c0b5011-34be-4fc7-91e4-e17f273ba971)

**Comment by ndesai-newrelic** [comment]
@jvega-omnipro we are unable to reproduce from our side, can you provide the sample app ? is it happening in production?

**Comment by jvega-omnipro** [comment]
@ndesai-newrelic No, I don't have a way to send you a sample application.
The project is being updated to version 3.24.2 of flutter - dart 3.5.2 and the gradle migration is in progress. In this process we encounter this error

**Comment by ndesai-newrelic** [comment]
@jvega-omnipro we are using same configuration and can you please share your apk file?

**Comment by ndesai-newrelic** [comment]
@jvega-omnipro we are unable to reproduce this issue.
