### ISSUE TITLE
Logs of external library are stored when the platform is Android

### ISSUE THREAD

**Issue by hohoins** [newrelic/newrelic-flutter-agent#130]
***
1. Problem
I am developing a Flutter App.
I am sending logs using NewrelicMobile.instance.logXXX().
However, logs that I did not send are also being saved.
The problem is that the logs that I did not send are being saved several times more than the logs that I sent.
The problem is quite urgent.
A storage capacity exceeded warning is occurring in Newrelic.
I need to solve this problem.

***
2. Analysis
As a result of the confirmation, the logs that I did not send were being sent from the android external library.
What has been confirmed so far is that when the android external library calls android.util.Log, they are saved in the Newrelic log.

***
3. Is there a solution?
I want to exclude logs sent from the android external library.
Is there a way to solve this?
Please check.

***
4. Logs I sent
<img width="300" alt="스크린샷 2024-12-09 오후 3 55 41" src="https://github.com/user-attachments/assets/c5e00804-196e-4ad7-9370-b7753ecf472f">

***
5. Logs I didn't send
<img width="300" alt="스크린샷 2024-12-09 오후 3 55 49" src="https://github.com/user-attachments/assets/a88e4e30-f073-4a68-8e1a-3c3a1c831846">

***

**Comment by hohoins** [comment]
@ndesai-newrelic 
Excuse me, could you help me? 🙇🙇🙇

**Comment by ndesai-newrelic** [comment]
@hohoins you can use this solution for now. https://github.com/newrelic/newrelic-android-agent/issues/261#issuecomment-2317995400

We are actively working on to add build time flag for log Instrumentation.

**Comment by hohoins** [comment]
There was a duplicate issue. Thank you. I will ask a question in issue #261.

**Comment by hohoins** [comment]
There was a duplicate issue. Thank you. I will ask a question in issue #261.
