### ISSUE TITLE
Does not work for flutter web.

### ISSUE THREAD

**Issue by ADAMC133** [newrelic/newrelic-flutter-agent#57]
Getting lots of errors like 
```
UnsupportedError (Unsupported operation: Platform._version)
```
I think this is because `import 'dart:io';` is not compatible with web. I've tried swapping out all of those imports with `import 'package:universal_io/io.dart';` But then its throwing

```
Launching lib/main.dart on Chrome in debug mode...
lib/main.dart:1
: Error: The argument type 'HttpClient/*1*/' can't be assigned to the parameter type 'HttpClient/*2*/?'.
../lib/newrelic_http_overrides.dart:26
 - 'HttpClient/*1*/' is from 'dart:_http'.
- 'HttpClient/*2*/' is from 'package:universal_io/src/http_client.dart' ('../../../../../.pub-cache/hosted/pub.dev/universal_io-2.2.2/lib/src/http_client.dart').
package:universal_io/src/http_client.dart:1
            ? createHttpClientFn!(context!)
```

Is there any ways to get this working with Web?

**Comment by ndesai-newrelic** [comment]
@ADAMC133 Our present plugin does not provide support for Flutter Web. However, please refer to the following documentation to learn how to enable Flutter Web monitoring: https://docs.newrelic.com/docs/browser/browser-integrations/flutter-web-integration/.

**Comment by ADAMC133** [comment]
The problem with flutter-web-intergration is that its just including a script in the HTML. Lets say I want to log a metric for how long it take a widget build to run? how would you recommend that implementation?

**Comment by JohnnyBravoFromTexas** [comment]
Hi @ADAMC133.  At this time we do not provide support for Flutter web integration with the mobile agent.  Our support is focused on Flutter for iOS and Android.   I have created a feature request to help us track this ask.  Although I do not have a timeline to share please know it's in our backlog.  Thanks for sharing!

**Comment by yuhao-nyc** [comment]
> Hi [@ADAMC133](https://github.com/ADAMC133). At this time we do not provide support for Flutter web integration with the mobile agent. Our support is focused on Flutter for iOS and Android. I have created a feature request to help us track this ask. Although I do not have a timeline to share please know it's in our backlog. Thanks for sharing!

any updates on Flutter web analytics tracking?

**Comment by yuhao-nyc** [comment]
@ADAMC133 Although the repo still don't support Flutter web but you can still call the NR JS lib through JS_Interop. for more context https://github.com/newrelic/newrelic-flutter-agent/issues/135
