### ISSUE TITLE
MacOS support

### ISSUE THREAD

**Issue by envomer** [newrelic/newrelic-flutter-agent#62]
Hey thanks for the cool flutter implementation.

I was wondering whether you plan on supporting MacOS as well?

**Comment by JohnnyBravoFromTexas** [comment]
Hi, Envomer.  Connecting the dots above... you are asking for Flutter support on MacOS?  Or just MacOS instrumentation?  Thanks!

**Comment by envomer** [comment]
Hey Johnny.

Now that flutter also supports building macos apps, i was curious for a newrelic flutter support for macos apps.

Is that something you plan on supporting as well in the near future?

**Comment by ndesai-newrelic** [comment]
@envomer we support Mac Catalyst linked apps, not native macOS.

**Comment by larryaasen** [comment]
Any plans to add support for macOS now?
@ndesai-newrelic @JohnnyBravoFromTexas
