### ISSUE TITLE
GoRouter observer causes exception

### ISSUE THREAD

**Issue by mohadel92** [newrelic/newrelic-flutter-agent#68]
while adding
`observers: <NavigatorObserver>[NewRelicNavigationObserver()],`

to the `go_router` in my project :

an exception while navigation to one of my screens
:
`package:flutter/src/widgets/navigator.dart': Failed assertion: line 2993 pos 18: '!navigator._debugLocked': is not true.`

any help with this issue

═══════ Exception caught by widgets library ═══════════════════════════════════
The following NoSuchMethodError was thrown building InheritedGoRouter(goRouter: Instance of 'GoRouter'):
Class 'RouteSettings' has no instance getter 'key'.
Receiver: Instance of 'RouteSettings'
Tried calling: key

The relevant error-causing widget was:
    MaterialApp MaterialApp:file:///Users/mohammedadelalisorour/Documents/My%20%20Work/Flutter/sevenSquare/the_laundry_hub/lib/app.dart:30:30

When the exception was thrown, this was the stack:
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
object_patch.dart:38
#1      NewRelicNavigationObserver._addGoRouterBreadcrumb (package:newrelic_mobile/newrelic_navigation_observer.dart:83:30)
newrelic_navigation_observer.dart:83
#2      NewRelicNavigationObserver.didPush (package:newrelic_mobile/newrelic_navigation_observer.dart:45:9)
newrelic_navigation_observer.dart:45
#3      _NavigatorPushObservation.notify (package:flutter/src/widgets/navigator.dart:3338:14)
navigator.dart:3338
#4      List.forEach (dart:core-patch/growable_array.dart:416:8)
growable_array.dart:416
#5      NavigatorState._flushObserverNotifications (package:flutter/src/widgets/navigator.dart:4333:27)
navigator.dart:4333
#6      NavigatorState._flushHistoryUpdates (package:flutter/src/widgets/navigator.dart:4295:5)
navigator.dart:4295
#7      NavigatorState._updatePages (package:flutter/src/widgets/navigator.dart:4161:5)
navigator.dart:4161
#8      NavigatorState.didUpdateWidget (package:flutter/src/widgets/navigator.dart:3803:7)
navigator.dart:3803
#9      StatefulElement.update (package:flutter/src/widgets/framework.dart:5643:55)
.....
..
..

════════ Exception caught by Flutter framework ═════════════════════════════════
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 2993 pos 18: '!navigator._debugLocked': is not true.
════════════════════════════════════════════════════════════════════════════════
D/newrelic(23857): PayloadController: 0ms. waiting to submit payload [8d20ef85-ac51-4a28-b6aa-c8093ea521dd].
D/newrelic(23857): HarvestTimer: time since last tick: 59997
D/newrelic(23857): Harvest: tick
D/newrelic(23857): Harvester state: CONNECTED
I/newrelic(23857): Harvester: connected
I/newrelic(23857): Harvester: Sending [8] HTTP transactions.
I/newrelic(23857): Harvester: Sending [0] activity traces.
I/newrelic(23857): Harvester: Sending [0] session attributes.
I/newrelic(23857): Harvester: Sending [0] analytics events.

**Comment by mohadel92** [comment]
when i remove the observer everything is working fine

**Comment by ndesai-newrelic** [comment]
@mohadel92 are you still seeing this issue?

**Comment by ndesai-newrelic** [comment]
@mohadel92 can you check this https://github.com/flutter/flutter/issues/108544?

**Comment by bernardoveras** [comment]
same problem

**Comment by duraz0rz** [comment]
Not the OP, but we're seeing a similar issue with using `go_router` for a modal bottom sheet.

When you use `showModalBottomSheet`, it [can potentially push a route to the Navigator where the settings do not have a route path or name](https://github.com/flutter/flutter/blob/d1d96059745a219ac954ddeea49d2a57237f4ed2/packages/flutter/lib/src/material/bottom_sheet.dart#L1259). For us, we're using `showModalBottomSheet` to pop up a widget, then when the user presses a button on that widget, we navigate to another page.

I believe the difference between `Navigator` and `go_router` when `NewRelicNavigationObserver` intercepts the route is that the `Navigator` path expects `RouteSettings` while the `go_router` path expects a widget.

![image](https://github.com/newrelic/newrelic-flutter-agent/assets/1535249/e3f2bd5d-8030-44b9-b5a0-aab86256209f)

**Comment by ndesai-newrelic** [comment]
@duraz0rz that's good feedback, i will check it from our side.

**Comment by duraz0rz** [comment]
To add a bit more to this, we figured out a workaround on our end. 

The [docs for showBottomModalSheet](https://api.flutter.dev/flutter/material/showModalBottomSheet.html) state that you can pass `routeSettings` for NavigationObservers: 

> The optional settings parameter sets the [RouteSettings](https://api.flutter.dev/flutter/widgets/RouteSettings-class.html) of the modal bottom sheet sheet. This is particularly useful in the case that a user wants to observe [PopupRoute](https://api.flutter.dev/flutter/widgets/PopupRoute-class.html)s within a [NavigatorObserver](https://api.flutter.dev/flutter/widgets/NavigatorObserver-class.html).

We didn't have this set when we were using `Navigator` and `NewRelicNavigationObserver` was not crashing, while it was crashing until we set `routeSettings` for a bottom sheet modal when we switched to `go_router`.

**Comment by ndesai-newrelic** [comment]
@duraz0rz @bernardoveras @mohadel92  can you check this in our latest flutter release?

**Comment by ndesai-newrelic** [comment]
@eugenio-tesio-ueno can you share example app or code snippet for this issue?

**Comment by MiguelBelotto00** [comment]
Hello @ndesai-newrelic , I hope you are feeling well.

This actually works for me by changing the child and key parameter that by default it does not bring in the routesettings.
![code](https://github.com/newrelic/newrelic-flutter-agent/assets/84353662/bdd8f937-e852-42f9-b228-59d0dc6562ab)

you know why you are looking for a child or key?.

It seems that the ModalBottomSheets use by default the RouteSettings class that has flutter with only the `name, arguments` property.

![code2](https://github.com/newrelic/newrelic-flutter-agent/assets/84353662/49073824-cd5e-48d8-8ab8-58c7094a96dd)

**Comment by ndesai-newrelic** [comment]
@MiguelBelotto00 you are right, we need to look for name instead of key, can you create PR for this?

**Comment by MiguelBelotto00** [comment]
Yes, for sure I prepare the pr of this

**Comment by eugenio-tesio-ueno** [comment]
> @eugenio-tesio-ueno can you share example app or code snippet for this issue?

Miguel will provide the error found https://github.com/newrelic/newrelic-flutter-agent/issues/68#issuecomment-2059466094

**Comment by ndesai-newrelic** [comment]
@MiguelBelotto00 that's right, you can remove the method, now we are reading it from the name so we dont need different method.

**Comment by ndesai-newrelic** [comment]
Hey @MiguelBelotto00, it seems like route.child is providing the same value as name when passed. If you have any alternative suggestions, feel free to open a PR, and we'll review it.

**Comment by eugenio-tesio-ueno** [comment]
If you took `_addGoRouterBreadcrumb` and cast `fromRoute` and `toRoute` as `RouteSettings`, you'll get a syntax error, like this:

![image](https://github.com/newrelic/newrelic-flutter-agent/assets/150923676/bd85cadd-b7ed-44ce-bf86-e217d24c27fc)

**Comment by eugenio-tesio-ueno** [comment]
The workaround is to copy the `NewRelicNavigationObserver` and create your own observer. So I guess this issue isn't critical

**Comment by ndesai-newrelic** [comment]
@eugenio-tesio-ueno why are you casting this as route settings for from route and to route?

**Comment by eugenio-tesio-ueno** [comment]
> @eugenio-tesio-ueno why are you casting this as route settings for from route and to route?

To convert the dynamic `fromRoute` variable to `RouteSettings`, (previously validated by the if condition) and to show you that `key` property does not exists.
