### ISSUE TITLE
Support android plugin DSL in flutter 3.19 

### ISSUE THREAD

**Issue by everfinal88** [newrelic/newrelic-flutter-agent#77]
Latest Flutter version 3.19 has been released recently. 
Among the changes, there is 1 mentioning about deprecated gradle plugin :
[Deprecated imperative apply of Flutter's Gradle plugins](https://docs.flutter.dev/release/breaking-changes/flutter-gradle-plugin-apply)
 
I've try to migrate it according to the flutter doc but new relic failed with exceptions.

```
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\User\MeoStudio\pure360-app-v2\android\app\build.gradle' line: 6

* What went wrong:
An exception occurred applying plugin request [id: 'com.newrelic.agent.android']
> Failed to apply plugin 'com.newrelic.agent.android'.
   > Could not create plugin of type 'NewRelicGradlePlugin'.
      > No such property: logger for class: com.newrelic.agent.InstrumentationAgent
```

Here's my settings.gradle
```
plugins {
    id "dev.flutter.flutter-plugin-loader" version "1.0.0"
    id "com.android.application" version "7.4.2" apply false
    id "org.jetbrains.kotlin.android" version "1.7.10" apply false
    id "com.google.gms.google-services" version "4.3.15" apply false
    id "com.newrelic.agent.android" version "7.0.0" apply false
}
```
Here's my app/build.gradle
```
plugins {
    id "com.android.application"
    id "kotlin-android"
    id "dev.flutter.flutter-gradle-plugin"
    id "com.google.gms.google-services"
    id "com.newrelic.agent.android"
}
```

Please update the android implementation or let me know what should I do for the migration. At the moment, I'll continue using flutter 3.16. Thanks

**Comment by ndesai-newrelic** [comment]
> @LanShunoda A suggested workaround to use the `plugins` closure:
> 
> The Android agent plugin is not yet published to the Gradle Plugin Portal (we plan on doing this later this year), so until this is done you will have to provide the classpath to the plugin either through the buildscript DSL (as documented), or in settings.gradle(.kts) through the pluginManagement closure:
> 
> ```
> pluginManagement {
>   var nr_version = "7.1.+"
> 
>   repositories {
>     mavenCentral()
>   }
>   resolutionStrategy {
>     eachPlugin {
>       if (requested.id.id.startsWith("newrelic")) {
>         useModule("com.newrelic.agent.android:agent-gradle-plugin:${nr_version}")
>       }
>     }
>   }
> 
>   // optiional: define here or root level build
>   plugins {
>     id("newrelic") version "${nr_version}"
>   }
> }
> ```
> 
> Then, the New Relic plugin can be declared in either pluginManagement (above), or the project level gradle build file:
> 
> ```
> pluginManagement {
>   var nr_version = "7.+"
> 
>   repositories {
>     mavenCentral()
>   }
>   resolutionStrategy {
>     eachPlugin {
>       if (requested.id.id.startsWith("newrelic")) {
>         useModule("com.newrelic.agent.android:agent-gradle-plugin:${nr_version}")
>       }
>     }
>   }
> 
>   // optiional: define here or root level build
>   plugins {
>     id("newrelic") version "${nr_version}"
>   }
> }
> 
> plugins {
>   id("com.android.application") version "8.1.+ apply false
>   id("org.jetbrains.kotlin.android") version "1.8.0" apply false
>   id("newrelic") version "<version>" apply false
> }
> ```
> 
> And then applied in the app-level build file with:
> 
> ```
> // Top-level build file where you can add configuration options common to all sub-projects/modules.
> plugins {
>     id("com.android.application")
>     id("org.jetbrains.kotlin.android")
>     id("newrelic")
> }
> ```

**Comment by everfinal88** [comment]
Thanks for the quick response, the provided solution works perfectly.
