### ISSUE TITLE
unable to send logs using the NewRelic Mobile SDK.

### ISSUE THREAD

**Issue by hohoins** [newrelic/newrelic-flutter-agent#78]
I am unable to send logs using the NewRelic Mobile SDK.
Does NewRelic Mobile SDK support sending custom text message logs?
I couldn't find the log transfer API in the sdk.
I wonder how I can transmit log messages.

exaple log
![log_example](https://github.com/newrelic/newrelic-flutter-agent/assets/3438181/14d72170-2c26-40dc-bd60-8ff336754d2f)

**Comment by ndesai-newrelic** [comment]
@hohoins are you using logs api to send logs? our current logs api supports TLS 1.2.

**Comment by hohoins** [comment]
> @hohoins Are you currently utilizing our Logs API for transmitting logs? Please note that our existing Logs API supports TLS 1.2. We're excited to announce plans to incorporate logs functionality for mobile in the next quarter. As developments unfold and this feature becomes available, we will provide updates here.

Thank you very much for your reply. 👍👍👍👍👍 

What I understand is below:
Currently, newrelic-flutter-agent does not have a log transmission function.
The log message function will be added to newrelic-flutter-agent in the next quarter, 2024.4 - 2024.6.
If I want to send a log message right now, I have to implement the log API myself.
Is this correct?

Then, we will wait for the log message sending function to be added in the next quarter.
thank you 🙇🙇🙇

**Comment by ndesai-newrelic** [comment]
@hohoins we are automatically collected print statement as custom event ,you can do query using  this **SELECT * FROM `Mobile Dart Console Events` SINCE 30 MINUTES AGO**

**Comment by hohoins** [comment]
> @hohoins we are automatically collected print statement as custom event ,you can do query using this **SELECT * FROM `Mobile Dart Console Events` SINCE 30 MINUTES AGO**

Does this mean that logs are automatically collected when using 'NewrelicMobile.instance.recordCustomEvent()'?
After this, I can check using the query 'SELECT * FROM Mobile Dart Console Events SINCE 30 MINUTES AGO'.
I couldn't check the log using recordCustomEvent().

I was able to check the log when I directly called 'https://log-api.newrelic.com/log/v1.'

"plans to incorporate logs functionality for mobile in the next quarter."
I look forward to the rapid integration of the LOG API into the newRelic mobile sdk.

thank you

**Comment by ndesai-newrelic** [comment]
yes, if you are using print statement anywhere in the flutter, we will automatically collected those statement as logs.

**Comment by ndesai-newrelic** [comment]
@hohoins We're excited to announce the release of mobile logs for our Flutter agent. You can now enable this feature in your application settings page on the New Relic platform. This new capability allows you to capture and analyze logs directly from your Flutter mobile applications, providing deeper insights into your app's behavior.
To enable mobile logs:

1. Log into your New Relic account
2. Navigate to your application settings page for mobile apps
3. Look for the mobile logs option
4. Enable the feature

If you have any questions about this new feature or need assistance enabling it, please don't hesitate to reach out to our support team. We're here to help you make the most of this powerful new tool.

**Comment by hohoins** [comment]
> @hohoins We're excited to announce the release of mobile logs for our Flutter agent. You can now enable this feature in your application settings page on the New Relic platform. This new capability allows you to capture and analyze logs directly from your Flutter mobile applications, providing deeper insights into your app's behavior. To enable mobile logs:
> 
> 1. Log into your New Relic account
> 2. Navigate to your application settings page for mobile apps
> 3. Look for the mobile logs option
> 4. Enable the feature
> 
> If you have any questions about this new feature or need assistance enabling it, please don't hesitate to reach out to our support team. We're here to help you make the most of this powerful new tool.

I'll check it out. Thank you.
👍👍👍👍👍👍👍👍👍

**Comment by hohoins** [comment]
@ndesai-newrelic   
Thank you very much. 👍👍👍👍👍

I am trying to apply the API transmission function to the product.
flutter package newrelic_mobile: 1.1.1
I checked the log function.
The result is that the log is recorded normally.

If the log cannot be sent due to network blocking, etc., it is temporarily stored and then transmitted to the server, right?
I asked a question for confirmation.

The result I checked is that when the device's newtwork is turned off, if the log API is called, it is stored as permanent data and the log is transmitted when the network is turned on again.

**Comment by ndesai-newrelic** [comment]
@hohoins it will record the log even if application does not have network.

**Comment by agilst** [comment]
Logs are not recorded on NewRelic using `newrelic_mobile: ^1.1.3`
 
<img width="1440" alt="Screenshot 2024-09-26 at 11 45 34" src="https://github.com/user-attachments/assets/545be59c-4078-4941-b6ae-e37265d7c4e0">
Here is my NewRelic init: 

```
  Config config = Config(accessToken: appToken);

  runZonedGuarded(() async {
    WidgetsFlutterBinding.ensureInitialized();
    FlutterError.onError = NewrelicMobile.onError;
    await NewrelicMobile.instance.startAgent(config);
    runApp(const MyApp());
  }, (Object error, StackTrace stackTrace) {
    NewrelicMobile.instance.recordError(error, stackTrace);
  });

```

and here is I used for logging:
`NewrelicMobile.instance.logInfo('Navigate to: $_currentIndex');`
I noticed that `.logInfo` using `print()` statement so I assumed it will be recorded to NewRelic. Is there anything I missed?

**Comment by hohoins** [comment]
> @ndesai-newrelic Logs are not recorded on NewRelic using `newrelic_mobile: ^1.1.3` and tested using iPhone Simulator
> 
> <img alt="Screenshot 2024-09-26 at 11 45 34" width="1440" src="https://private-user-images.githubusercontent.com/153470171/370988507-545be59c-4078-4941-b6ae-e37265d7c4e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMjg0OTcsIm5iZiI6MTcyNzMyODE5NywicGF0aCI6Ii8xNTM0NzAxNzEvMzcwOTg4NTA3LTU0NWJlNTljLTQwNzgtNDk0MS1iNmFlLWUzNzI2NWQ3YzRlMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNlQwNTIzMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05M2FiNmY1ODhjNjNiMmQyNTM0OGIxYmVkM2QyMzMxN2VkZjMwNTIwYmJkOGYwOTA2YTllNzQwOGQzY2JiM2VkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.SpOcGEccmaNxnXFDRpLZV-Es7xrQp_Nq0kHJcAPKASY"> Here is my NewRelic init:
> ```
>   Config config = Config(accessToken: appToken);
> 
>   runZonedGuarded(() async {
>     WidgetsFlutterBinding.ensureInitialized();
>     FlutterError.onError = NewrelicMobile.onError;
>     await NewrelicMobile.instance.startAgent(config);
>     runApp(const MyApp());
>   }, (Object error, StackTrace stackTrace) {
>     NewrelicMobile.instance.recordError(error, stackTrace);
>   });
> ```
> 
> and here is I used for logging: `NewrelicMobile.instance.logInfo('Navigate to: $_currentIndex');` I noticed that `.logInfo` using `print()` statement so I assumed it will be recorded to NewRelic. Is there anything I missed?

Have you enabled the logging feature for the entity?
Application> Mobile Logs> switch on

<img width="1640" alt="스크린샷 2024-09-26 오후 2 26 38" src="https://github.com/user-attachments/assets/4e3e4f47-fb5d-4bae-ac59-d7eadadab622">

**Comment by agilst** [comment]
OK my bad it's not enabled on my Settings. I assumed my issue is resolved. 
thanks for your support!
<img width="906" alt="Screenshot 2024-09-26 at 12 46 15" src="https://github.com/user-attachments/assets/ff586401-e209-44f9-8c1f-e507f74ed172">
