### ISSUE TITLE
TMS-91056: Invalid privacy manifest - The PrivacyInfo.xcprivacy

### ISSUE THREAD

**Issue by thanhnt-mdev** [newrelic/newrelic-flutter-agent#85]
I got below error when submitting IOS app for review. Please help to check.

TMS-91056: Invalid privacy manifest - The PrivacyInfo.xcprivacy file from the following path is invalid: “Frameworks/NewRelic.framework/PrivacyInfo.xcprivacy”. Keys and values in any privacy manifest must be in a valid format. For more details about privacy manifest files, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files.

**Comment by ndesai-newrelic** [comment]
@thanhnt-mdev which version of newrelic flutter agent are you using?

**Comment by thanhnt-mdev** [comment]
@ndesai-newrelic I just have updated to latest version 1.0.8 and it's working.
Great work. Thank you
