### ISSUE TITLE
Newrelic.properties was not found! Mapping file for variant [devRelease] not uploaded.

### ISSUE THREAD

**Issue by ItsNotPat** [newrelic/newrelic-flutter-agent#98]
I migrated my gradle from Gradle **7.3** to **8.0**.

I encountered this problem with new relic.

> Execution failed for task ':app:minifyReleaseWithR8'.

I found this [Git Issue](https://github.com/newrelic/newrelic-flutter-agent/issues/63) that fixed my problem. I added a proguard-rules.pro file in my app folder and also indicated it on my app level build.gradle

**proguard-rules.pro**

``` 
-dontwarn com.newrelic.agent.android.ndk.AgentNDK$Builder
-dontwarn com.newrelic.agent.android.ndk.AgentNDK
-dontwarn com.newrelic.agent.android.ndk.AgentNDKListener

-keep class org.apache.http.** { *; }
-dontwarn org.apache.http.**

-keep class com.squareup.okhttp.* { *; }
-dontwarn com.squareup.okhttp.**
-dontwarn okio.**

-keep class okhttp3.** { *; }
-dontwarn okhttp3.**
-dontwarn okio.**

-keep class retrofit2.** { *; }
-dontwarn retrofit2.** 
```

After I applied this fix I still encounter the newrelic.properties error.

**Comment by ndesai-newrelic** [comment]
@ItsNotPat did you add newrelic.properties file for your project?

**Comment by nmpco129** [comment]
hello @ndesai-newrelic , do you have an example for `newrelic.properties` file?
I can not find it in your `example` app on github. Thanks a lot

**Comment by ndesai-newrelic** [comment]
please follow this: https://docs.newrelic.com/docs/mobile-monitoring/new-relic-mobile-android/install-configure/android-agent-crash-reporting/#mapping-file

**Comment by ItsNotPat** [comment]
I did not add newrelic.properties to my flutter project. Ill try to follow the instructions above.

**Comment by mtpultz-dunbar** [comment]
@ndesai-newrelic do we need to add a mapping file for Flutter applications?  The NewRelic Flutter docs don't indicate this https://docs.newrelic.com/docs/mobile-monitoring/new-relic-mobile-flutter/monitor-your-flutter-application as needed.  Is this related to signing application and the process of minification/shrinkifying using R8 that requires we consult the Android mobile docs and add a mapping file?  I only asking since it isn't intuitive or documented.

**Comment by ndesai-newrelic** [comment]
@mtpultz-dunbar  If you want to symbolicate your Android crashes, you need to upload your mapping file. Our Android documentation already includes a section on this topic: [Symbolicate Android Crashes](https://docs.newrelic.com/docs/mobile-monitoring/new-relic-mobile-android/install-configure/android-agent-crash-reporting/#mapping-file).
