### ISSUE TITLE
How to create a custom Navigation Observer?

### ISSUE THREAD

**Issue by SAGARSURI** [newrelic/newrelic-flutter-agent#99]
Hey team,
I am planning to use auto_route and want to integrate new_relic for monitoring app metrics. How can I create my own custom navigation observer? I see that you guys have a direct dependency on go_router.

**Comment by codingstark-dev** [comment]
samee issue please some one fix this!

> Hey team, I am planning to use auto_route and want to integrate new_relic for monitoring app metrics. How can I create my own custom navigation observer? I see that you guys have a direct dependency on go_router.

**Comment by codingstark-dev** [comment]
> Hey team, I am planning to use auto_route and want to integrate new_relic for monitoring app metrics. How can I create my own custom navigation observer? I see that you guys have a direct dependency on go_router.
I think you can do this approach 
`import 'package:auto_route/auto_route.dart';

import 'package:flutter/material.dart';

class RoutingObserver extends AutoRouterObserver {
  @override
  void didPush(Route<dynamic> targetRoute, Route<dynamic>? previousRoute) {
    print('did push: ${targetRoute.settings.arguments}');
  }
}`

**Comment by SAGARSURI** [comment]
Yeah I agree with your approach and that's how I am implementing right now. But if the package can build some abstraction and we can directly use without depending on a specific routing library. It would be great!

**Comment by ndesai-newrelic** [comment]
@SAGARSURI we will add support for auto_route in future releases.

**Comment by ndesai-newrelic** [comment]
@SAGARSURI 

New Relic's agent for Flutter applications offers automatic route capture functionality when using the auto_route package. To enable this feature, you need to configure the navigation observer in your app's router setup. Here's how you can do it:

```dart
MaterialApp.router(
  routerConfig: AppRouter().config(
    navigatorObservers: () => [NewRelicNavigationObserver()],
  ),
),
```

By adding the `NewRelicNavigationObserver()` to the `navigatorObservers` list in your `AppRouter` configuration, you allow New Relic to automatically capture route information in your Flutter app.

This setup integrates New Relic's monitoring capabilities with your app's navigation system, providing insights into user journeys and app flow.
